const express=require("express");
const korisnikController = require("../controllers/KorisnikController");
const {pretragaPrikazi} = require("../controllers/RedVoznjeController");
let router=express.Router();
router.get('/prijava',korisnikController.prijava);
router.get('/registracija',korisnikController.registracija);
router.post('/prijava',korisnikController.prijavi_korisnika);
router.post('/registracija',korisnikController.registruj);
router.post('/odjava',korisnikController.odjava);
router.get('/',pretragaPrikazi);
module.exports=router;